package AuthenticationApp;


/**
* AuthenticationApp/Authentication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, October 6, 2021 12:34:43 o'clock PM EDT
*/

public interface Authentication extends AuthenticationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Authentication
