package AuthenticationApp;


/**
* AuthenticationApp/AuthenticationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, October 6, 2021 12:34:43 o'clock PM EDT
*/

public interface AuthenticationOperations 
{
  boolean login (String username, String password);
  void shutdown ();
} // interface AuthenticationOperations
